TOP=..
include $(TOP)/configure/CONFIG
#=======================================

DB += devKeithley6482.db
DB += $(TOP)/Keithley6482Sup/devKeithley6482.proto

# Install .dbd and .db files
DB_INSTALLS += devKeithley6482.db
DB_INSTALLS += zeroCorrect.db
DB_INSTALLS += $(TOP)/Keithley6482Sup/devKeithley6482.proto

#=======================================
include $(TOP)/configure/RULES
