#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT-arm_zynq  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../../.. T_A=linuxRT-arm_zynq  $@

force:  ;
